sudo: required
services:
  - docker

before-install:
  - docker build -t hebbarchandrika/docker-react -f Dockerfile.dev .
script:
  - docker run  hebbarchandrika/docker-react npm run test -- --coverage
 